Try to ensure imageHeight is an integer.
OCR-D/ocrd_olena pull request #57
Opened 2020-06-12 07:43 UTC by j23d

Running into an error in core while validating the image height inserted using `identify`:

`
13:01:30.945 INFO processor.TesserocrSegmentRegion - INPUT FILE 0 / PHYS_0001
13:01:30.946 DEBUG ocrd.workspace - download_file <OcrdFile mimetype=application/vnd.prima.page+xml, ID=FILE_0001_OCR-D-IMG-BINPAGE, url=OCR-D-IMG-BINPAGE/FILE_0001_OCR-D-IMG-BINPAGE.xml, local_filename=OCR-D-IMG-BINPAGE/FILE_0001_OCR-D-IMG-BINPAGE.xml]/>  [_recursion_count=0]
Traceback (most recent call last):
  File "/home/j23d/projects/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/ocrd_models/ocrd_page_generateds.py", line 203, in gds_parse_integer
    ival = int(input_data)
ValueError: invalid literal for int() with base 10: '1136+0+0'`

Better ideas than cutting the offending `+0+0` are welcome, but this works for me.

2020-06-12 07:48 UTC, kba approved these changes

2020-06-12 07:49 UTC, kba approved these changes

2020-06-12 08:05 UTC, bertsky requested changes
Strange. This is not supposed to happen. When `ocrd-olena-binarize` gets to create a fresh PAGE-XML from a pure image file, it uses ImageMagick `identify` to retrieve the image size. But the third word (array result index 2) does not contain geometry (`+0+0`) in my version of IM (but the fourth does).

Which version do you have?

2020-06-12 08:22 UTC, bertsky commented
> But the third word (array result index 2) does not contain geometry (`+0+0`) in my version of IM (but the fourth does).
> 
> Which version do you have?

Or rather, what kind of image file does this happen with?

I cannot think of any way that the fourth word becomes the third in the `identify` result – other than because IM does not recognize the format of the image:

https://github.com/ImageMagick/ImageMagick/blob/6c80c0ca8e31fae30e0ff34f74ac83dc48bd4eca/MagickCore/identify.c#L610-L637

2020-06-12 08:26 UTC, kba commented
If it is a version issue, I can amend https://github.com/OCR-D/ocrd_olena/pull/53 to check version as well. If it's a problem with the image, it would help to see `OCR-D-IMG-BINPAGE/FILE_0001_OCR-D-IMG-BINPAGE.xml` and the images - I assume that it's the original image but if the image was produced by an OCR-D processor, it's worth making sure there's no image-corrupting bug in core.

2020-06-12 10:03 UTC, j23d commented
> Strange. This is not supposed to happen. When `ocrd-olena-binarize` gets to create a fresh PAGE-XML from a pure image file, it uses ImageMagick `identify` to retrieve the image size. But the third word (array result index 2) does not contain geometry (`+0+0`) in my version of IM (but the fourth does).

Seems be a version problem. `identify` output on my console only give the image size including the geometry. 

```
j23d@b-ms120:/tmp$ identify /tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png 
/tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png PNG 800x1136+0+0 DirectClass 16-bit 42.9Ki 0.000u 0m:0.000008s
```

> Which version do you have?

```
j23d@b-ms120:/tmp$ identify --version
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
j23d@b-ms120:/tmp$ cat /etc/debian_version 
bullseye/sid
```

What about using `-format`?
```
j23d@b-ms120:/tmp$ identify -format "%[fx:w]x%[fx:h]" /tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png
800x1136
```

2020-06-12 10:24 UTC, bertsky commented
> Seems be a version problem. 

But I have already tried that very version (it's also distributed with Ubuntu 19.10 "eoan").

> `identify` output on my console only give the image size including the geometry.
> 
> ```
> j23d@b-ms120:/tmp$ identify /tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png 
> /tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png PNG 800x1136+0+0 DirectClass 16-bit 42.9Ki 0.000u 0m:0.000008s
> ```

This becomes even more awkward:
- Why is the order reversed in the later columns?
- Why is your binarized PNG 16-bit? (What format was the original?)

> 
> > Which version do you have?
> 
> ```
> j23d@b-ms120:/tmp$ identify --version
> Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
> j23d@b-ms120:/tmp$ cat /etc/debian_version 
> bullseye/sid
> ```

Maybe this has something to do with `/etc/ImageMagick-6` configs?

> What about using `-format`?
> 
> ```
> j23d@b-ms120:/tmp$ identify -format "%[fx:w]x%[fx:h]" /tmp/ocrd_butler_results_testing/foobar567/OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola-ms-split.png
> 800x1136
> ```

Yes, this seems to be the only reasonable way out of this mess. Could you update (and force-push) your PR along those lines?

2020-06-12 12:06 UTC, j23d commented
>     * Why is the order reversed in the later columns?

The original image was derived from [https://content.staatsbibliothek-berlin.de/dc/PPN80041750X.mets.xml](https://content.staatsbibliothek-berlin.de/dc/PPN80041750X.mets.xml).

>     * Why is your binarized PNG 16-bit? (What format was the original?)

Did it like this:
```
(venv) j23d@b-ms120:/tmp/foo$ ocrd workspace clone https://content.staatsbibliothek-berlin.de/dc/PPN80041750X.mets.xml
13:08:49.499 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
/tmp/foo
(venv) j23d@b-ms120:/tmp/foo$ ocrd workspace find -G DEFAULT --download
13:13:54.326 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
DEFAULT/FILE_0001_DEFAULT.jpg
DEFAULT/FILE_0002_DEFAULT.jpg
(venv) j23d@b-ms120:/tmp/foo$ identify DEFAULT/FILE_0001_DEFAULT.jpg
DEFAULT/FILE_0001_DEFAULT.jpg JPEG 800x1136 800x1136+0+0 8-bit sRGB 791391B 0.030u 0:00.030
(venv) j23d@b-ms120:/tmp/foo$ ocrd-olena-binarize -I DEFAULT -O OLENA -p '{"impl":"sauvola"}'
13:14:32.735 INFO ocrd-olena-binarize - No output file group for images specified, falling back to 'OCR-D-IMG-BIN'
13:14:33.311 INFO ocrd-olena-binarize - processing image/jpg input file FILE_0001_DEFAULT (PHYS_0001)
13:14:34.007 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
13:14:35.162 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
13:14:35.235 INFO ocrd-olena-binarize - processing image/jpg input file FILE_0002_DEFAULT (PHYS_0002)
13:14:35.926 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
13:14:37.102 INFO ocrd.workspace - Saving mets '/tmp/foo/mets.xml'
(venv) j23d@b-ms120:/tmp/foo$ identify OCR-D-IMG-BIN/FILE_0001_OLENA-BIN_sauvola.png
OCR-D-IMG-BIN/FILE_0001_OLENA-BIN_sauvola.png PNG 800x1136 800x1136+0+0 16-bit sRGB 42046B 0.000u 0:00.000
```
And yes, there is the size also without geometry and I'm unable to reproduce the problem from yesterday I copy / pasted from the console window. Dunno whats the difference, versions and configs wasn't changed.

> > What about using `-format`?
> [...]
> Yes, this seems to be the only reasonable way out of this mess. Could you update (and force-push) your PR along those lines?

Done.
But as I'm not able to reproduce this I'm totally fine if you just close it.

2020-06-12 12:14 UTC, bertsky approved these changes
Thanks!

However you got there, it sounds chilling enough that I would prefer to avoid it, regardless how reproducible this is.

2020-06-12 12:15 UTC, bertsky commented
16-bit binarization from 8-bit JPEG – something must have gone very wrong back then...

2020-06-12 12:57 UTC, merged

2020-06-15 22:11 UTC, bertsky commented
> 16-bit binarization from 8-bit JPEG – something must have gone very wrong back then...

@j23d I cannot reproduce what happened to your JPEGs:

    ocrd workspace clone sbb-mets-PPN80041750X.xml
    ocrd workspace find -G DEFAULT --download
    ocrd-olena-binarize -I DEFAULT -O OLENA -p '{"impl":"sauvola"}'
    identify OCR-D-IMG-BIN/FILE_0001_OLENA-BIN_sauvola.png 

This gives me:
```
OCR-D-IMG-BIN/FILE_0001_OLENA-BIN_sauvola.png PNG 800x1136 800x1136+0+0 8-bit sRGB 2c 16.9KB 0.000u 0:00.000
```

No 16-bit quantization!

I've used:
```
ocrd-olena-binarize --version
Version "1.1.6", ocrd/core "2.10.2"
```

BTW, is it normal for your data provider to annotate wrong DPI meta-data? In the JPEGs, which are clearly some kind of downscaled compressed version of the original TIFF from Goobi, the tags say they contain 360 DPI pixel density (which at this pixel resolution would be a 2.2*3.2 inch printspace size on paper):
```
Image: DEFAULT/FILE_0001_DEFAULT.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 800x1136+0+0
  Resolution: 360x360
  Print size: 2.22222x3.15556
  Units: PixelsPerInch
```